### ISSUE TITLE
'LapsCore' and 'ASMR' in ICCV2021-PersonSearch part are not real 'Person Search' papers.

### ISSUE THREAD

**Issue by ZhengPeng7** [bismex/Awesome-person-re-identification#7]
These two works are both proposed to solve both actually person re-id/retrieval tasks, not the typical person search task (detection+re-id in a single step).

**Comment by bismex** [comment]
Thank you for your valuable comments. We found that a person search subject can be divided into a detection-based approach and a text-based approach. So, we have categorized person search papers by approach.
